import Header from '@/app/_components/reusable/Header';

export const metadata = {
  title: { template: '%s: TT Tech Talent', default: 'TT Tech Talent' },
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <>
      <Header border={true} />

      {/* <div className="flex-1 w-full bg-gradient-to-b from-primary-950 from-mh to-white to-90% via-slate-100 via-mh -z-30"> */}
      <main className="flex flex-col flex-1 w-full h-full mx-auto font-marcellus">
        {/* <main className="flex flex-col flex-1 w-full h-full px-4 py-4 mx-auto sm:px-8 sm:pt-10 max-w-7xl font-marcellus"> */}
        {children}
      </main>
      {/* </div> */}
    </>
  );
}
