import '@/app/_styles/globals.css';

import { raleway } from '@lib/fonts';

import Header from '@components/Header';

export const metadata = {
  title: { template: '%s: TT Tech Talent', default: 'TT Tech Talent' },
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${raleway} relative flex flex-col min-h-screen bg-primary-950 text-accent-50 font-raleway`}
      >
        <Header />
        <div className="grid flex-1 px-4 py-12 sm:px-8">
          <main className="w-full mx-auto max-w-7xl">{children}</main>
        </div>
      </body>
    </html>
  );
}
