import { Josefin_Sans } from 'next/font/google';

import '@/app/_styles/globals.css';

import Header from '@components/Header';

export const metadata = {
  title: { template: '%s: TT Tech Talent', default: 'TT Tech Talent' },
  description: 'Generated by create next app',
};

const josefin = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative flex flex-col min-h-screen bg-primary-950 text-primary-100">
        <Header />
        {children}
      </body>
    </html>
  );
}
