import '@/app/_styles/globals.css';
import { marcellus, quattrocento, raleway } from '@lib/fonts';

import Header from '@/app/_components/reusable/Header';

export const metadata = {
  title: { template: '%s: TT Tech Talent', default: 'TT Tech Talent' },
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <>
      <Header border={false} />

      <div className="absolute flex-1 w-full h-full">
        <main
          className={`flex-1 w-full h-full px-4 pt-24 mx-auto sm:px-8 sm:pt-28 max-w-7xl font-marcellus`}
        >
          {children}
        </main>
      </div>
    </>
  );
}
